global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'kafka-o11y-tutorial'
    environment: 'tutorial'

# Rule files for alerting
rule_files:
  # - "alert_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http

  # OpenTelemetry Collector metrics (application telemetry)
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
    metrics_path: /metrics
    scheme: http
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: otel-collector:8889

  # Kafka JMX metrics
  - job_name: 'kafka-jmx'
    scrape_interval: 15s
    static_configs:
      - targets: ['kafka-jmx-exporter:8080']
    metrics_path: /metrics
    scheme: http
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kafka-broker'
      - target_label: component
        replacement: 'kafka'

  # Zookeeper JMX metrics
  - job_name: 'zookeeper-jmx'
    scrape_interval: 15s
    static_configs:
      - targets: ['zookeeper-jmx-exporter:8081']
    metrics_path: /metrics
    scheme: http
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'zookeeper'
      - target_label: component
        replacement: 'zookeeper'

  # OpenTelemetry Collector internal metrics
  - job_name: 'otel-collector-internal'
    scrape_interval: 30s
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: /metrics
    scheme: http
