hostPort: zookeeper:9999
username: ""
password: ""
ssl: false
lowercaseOutputName: true
lowercaseOutputLabelNames: true

# Zookeeper metrics rules
rules:
  # Basic Zookeeper metrics
  - pattern: "org.apache.ZooKeeperService<name0=(.+), name1=(.+)><>(.+)"
    name: zookeeper_$1_$2_$3
    labels:
      cluster: "tutorial"
      instance: "zookeeper"
      component: "zookeeper"

  # Zookeeper server stats
  - pattern: "org.apache.ZooKeeperService<name0=(.+)><>(.+)"
    name: zookeeper_$1_$2
    labels:
      cluster: "tutorial"
      instance: "zookeeper"
      component: "zookeeper"

  # JVM metrics for Zookeeper
  - pattern: "java.lang<type=(.+), name=(.+)><>(.+)"
    name: zookeeper_jvm_$1_$2_$3
    labels:
      cluster: "tutorial"
      instance: "zookeeper"
      component: "jvm"

  # Garbage collection metrics
  - pattern: "java.lang<type=GarbageCollector, name=(.+)><>CollectionCount"
    name: zookeeper_jvm_gc_collection_count_total
    labels:
      cluster: "tutorial"
      instance: "zookeeper"
      component: "jvm"
      gc_name: $1

  - pattern: "java.lang<type=GarbageCollector, name=(.+)><>CollectionTime"
    name: zookeeper_jvm_gc_collection_time_total
    labels:
      cluster: "tutorial"
      instance: "zookeeper"
      component: "jvm"
      gc_name: $1

  # Memory metrics
  - pattern: "java.lang<type=Memory><>(.+)"
    name: zookeeper_jvm_memory_$1
    labels:
      cluster: "tutorial"
      instance: "zookeeper"
      component: "jvm" 